# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - dataset: seg
  - model: Spec2DCNN
  - feature_extractor: CNNSpectrogram
  - decoder: UNet1DDecoder
  - split: fold_0

seed: 42
exp_name: dummy
batch_size: 32
num_workers: 24
duration: 5760 # duration * 5 = 秒数
downsample_rate: 2
upsample_rate: 1

trainer:
  epochs: 30
  accelerator: auto
  use_amp: true
  debug: false
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  monitor: val_loss
  monitor_mode: min
  check_val_every_n_epoch: 1

dataset:
  name: seg
  batch_size: 64
  num_workers: 8
  offset: 10
  sigma: 10
  bg_sampling_rate: 0.5

aug:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

# post_process
pp:
  score_th: 0.02
  distance: 10

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "step"
  # - "month_sin"
  # - "month_cos"
  - "hour_sin"
  - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"
  # - "anglez_sin"
  # - "anglez_cos"

# optimizer
optimizer:
  lr: 0.0001

# scheduler
scheduler:
  num_warmup_steps: 10
